###############################################################################
#
#                       MC504 - Sistemas Operacionais 
#                Animacao que descreve o algoritmo paralelo
#                                 "nome"
#
###############################################################################

## makefile
LDFLAGS=-lncurses -lpthread

demo:
	gcc anim.c -o anim $(LDFLAGS)

final:
	gcc padaria_animada.c -o padaria_animada $(LDFLAGS)

clean:
	rm anim padaria_animada
