###############################################################################
#
#                       MC504 - Sistemas Operacionais 
#                Animacao que descreve o algoritmo paralelo
#                                 "nome"
#
###############################################################################

## makefile
LDFLAGS=-lncurses -lpthread

all: final

final:
	gcc padaria_animada.c -o padaria_animada $(LDFLAGS)

clean:
	rm -f padaria_animada
