###############################################################################
#
#                       MC504 - Sistemas Operacionais 
#                Animacao que descreve o algoritmo paralelo
#                                 "nome"
#
###############################################################################

## makefile
LDFLAGS=-lncurses

demo:
	gcc anim.c -o anim $(LDFLAGS)

clean:
	rm anim
